/*
 *
 */
package las;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Patrick Goodson
 */

public class UI extends javax.swing.JFrame
{

    /**
     * Creates new form UI
     */
    
    // Object declaration
    Cataloguer cataloguer;
    ExternalUser externalUser;
    Issuer issuer;
    ReportsManager reportsManager;
    SystemAdmin systemAdmin;
    
    
    // UI config
    static DefaultListModel typeModel = new DefaultListModel();
    // Index of listModel
    static int currentSelection = 0;
    public static CardLayout card = new CardLayout();
    
    public UI()
    {
        initComponents();
        card = (CardLayout) jPanelMain.getLayout();
        this.getRootPane().setDefaultButton(jButtonLogin);
        // Set up List Users
        typeModel.addElement("System Admin");
        typeModel.addElement("Reports Manager");
        typeModel.addElement("Cataloguer");
        typeModel.addElement("Issuer");
        typeModel.addElement("External User");
        jListUsers.setModel(typeModel);
        
        // Create a listener for when the user changes a selection in the list
        jListUsers.addListSelectionListener(new ListSelectionListener()
                {

                    @Override
                    public void valueChanged(ListSelectionEvent e)
                    {
                        if (!e.getValueIsAdjusting())
                        {
                            currentSelection = jListUsers.getSelectedIndex();
                            checkPasswordRequired(currentSelection);
                        }
                    }
            /**
             * Sets if a password is required for each user selection
             * @param eventSelection 
             */
            private void checkPasswordRequired(int eventSelection)
            {
                switch(eventSelection)
                {
                    case 0: jPasswordField.setEnabled(true);// Sys admin
                        break;
                    case 1: jPasswordField.setEnabled(true);// Reports manager
                        break;
                    case 2: jPasswordField.setEnabled(true);// Cataloguer
                        break;
                    case 3: jPasswordField.setEnabled(true);// Issuer
                        break;
                    case 4: jPasswordField.setEnabled(false);// External user
                }
            }

                });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanelMain = new javax.swing.JPanel();
        jPanelLogin = new javax.swing.JPanel();
        jLabelUserHint = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListUsers = new javax.swing.JList();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelPasswordHint = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jPanelSysAdmin = new javax.swing.JPanel();
        jLabelSysAdmin = new javax.swing.JLabel();
        jButtonAddMember = new javax.swing.JButton();
        jButtonRemoveMember = new javax.swing.JButton();
        jButtonChangePrivilege = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTextFieldSearch = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jLabelSearchHint = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelReportsManager = new javax.swing.JPanel();
        jLabelReportsManager = new javax.swing.JLabel();
        jButtonExport = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jButtonLogout1 = new javax.swing.JButton();
        jPanelCataloguer = new javax.swing.JPanel();
        jLabelCataloguer = new javax.swing.JLabel();
        jButtonLogout2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<String>();
        jTextFieldSearch2 = new javax.swing.JTextField();
        jButtonSearch2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<String>();
        jButtonAdd = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonChange = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanelIssuer = new javax.swing.JPanel();
        jLabelIssuer = new javax.swing.JLabel();
        jButtonLogout3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<String>();
        jButtonSearch3 = new javax.swing.JButton();
        jTextFieldSearch3 = new javax.swing.JTextField();
        jButtonIssue = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<String>();
        jTextFieldSearch5 = new javax.swing.JTextField();
        jPanelExternalUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<String>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<String>();
        jButtonLogout4 = new javax.swing.JButton();
        jTextFieldSearch4 = new javax.swing.JTextField();
        jButtonSearch4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMain.setLayout(new java.awt.CardLayout());

        jLabelUserHint.setText("Select user type:");

        jListUsers.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Systen Admin", "Reports Manager", "Cataloguer", "Issuer", "External User" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jListUsers);

        jLabelPasswordHint.setText("Password:");

        jButtonLogin.setText("Log In");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPasswordField)
                            .addComponent(jLabelPasswordHint, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addComponent(jLabelUserHint)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUserHint)
                .addGap(18, 18, 18)
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addGroup(jPanelLoginLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelPasswordHint)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLogin)))
                .addContainerGap())
        );

        jPanelMain.add(jPanelLogin, "-1");

        jLabelSysAdmin.setText("System Administrator");

        jButtonAddMember.setText("Add member");

        jButtonRemoveMember.setText("Remove member");

        jButtonChangePrivilege.setText("Change member");

        jList1.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jButtonSearch.setText("Search Member");

        jLabelSearchHint.setText("Search for member:");

        jButtonLogout.setText("Log Out");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSysAdminLayout = new javax.swing.GroupLayout(jPanelSysAdmin);
        jPanelSysAdmin.setLayout(jPanelSysAdminLayout);
        jPanelSysAdminLayout.setHorizontalGroup(
            jPanelSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSysAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSysAdminLayout.createSequentialGroup()
                        .addComponent(jLabelSearchHint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(177, 177, 177))
                    .addGroup(jPanelSysAdminLayout.createSequentialGroup()
                        .addGroup(jPanelSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSysAdmin)
                            .addGroup(jPanelSysAdminLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(jPanelSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonAddMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRemoveMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(jButtonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonChangePrivilege, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanelSysAdminLayout.setVerticalGroup(
            jPanelSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSysAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSysAdmin)
                .addGap(18, 18, 18)
                .addGroup(jPanelSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSearchHint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSearch)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelSysAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSysAdminLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddMember)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemoveMember)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonChangePrivilege)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(jButtonLogout))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jPanelMain.add(jPanelSysAdmin, "0");
        jPanelSysAdmin.getAccessibleContext().setAccessibleName("");

        jLabelReportsManager.setText("Reports manager");

        jButtonExport.setText("Export to excel");
        jButtonExport.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonExportActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Books issued / time", "Oversubscribed items / time", "New Catalogue items / time" }));

        jButtonLogout1.setText("Log Out");
        jButtonLogout1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonLogout1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelReportsManagerLayout = new javax.swing.GroupLayout(jPanelReportsManager);
        jPanelReportsManager.setLayout(jPanelReportsManagerLayout);
        jPanelReportsManagerLayout.setHorizontalGroup(
            jPanelReportsManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReportsManagerLayout.createSequentialGroup()
                .addGroup(jPanelReportsManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReportsManagerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(jButtonExport))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReportsManagerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanelReportsManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelReportsManager)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelReportsManagerLayout.setVerticalGroup(
            jPanelReportsManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReportsManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelReportsManager)
                .addGap(18, 18, 18)
                .addGroup(jPanelReportsManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonExport)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addComponent(jButtonLogout1)
                .addContainerGap())
        );

        jPanelMain.add(jPanelReportsManager, "1");

        jLabelCataloguer.setText("Cataloguer");

        jButtonLogout2.setText("Log Out");
        jButtonLogout2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonLogout2ActionPerformed(evt);
            }
        });

        jList2.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        jButtonSearch2.setText("Search");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Maintain Items", "Maintain Sources", " ", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Add...");

        jButtonRemove.setText("Remove");

        jButtonChange.setText("Change");

        jCheckBox1.setText("Email Users");

        javax.swing.GroupLayout jPanelCataloguerLayout = new javax.swing.GroupLayout(jPanelCataloguer);
        jPanelCataloguer.setLayout(jPanelCataloguerLayout);
        jPanelCataloguerLayout.setHorizontalGroup(
            jPanelCataloguerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCataloguerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCataloguerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCataloguerLayout.createSequentialGroup()
                        .addComponent(jLabelCataloguer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addGroup(jPanelCataloguerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLogout2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSearch2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCataloguerLayout.setVerticalGroup(
            jPanelCataloguerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCataloguerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCataloguerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCataloguer)
                    .addComponent(jTextFieldSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCataloguerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanelCataloguerLayout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemove)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonChange)
                        .addGap(27, 27, 27)
                        .addComponent(jCheckBox1)
                        .addGap(0, 141, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonLogout2)
                .addContainerGap())
        );

        jPanelMain.add(jPanelCataloguer, "2");

        jLabelIssuer.setText("Issuer");

        jButtonLogout3.setText("Log Out");
        jButtonLogout3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonLogout3ActionPerformed(evt);
            }
        });

        jList3.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList3);

        jButtonSearch3.setText("Search");

        jButtonIssue.setText("Issue Item(s)");

        jLabel3.setText("Staff/Student ID:");

        jLabel4.setText("Search By:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Title", "Author", "Item Type" }));

        javax.swing.GroupLayout jPanelIssuerLayout = new javax.swing.GroupLayout(jPanelIssuer);
        jPanelIssuer.setLayout(jPanelIssuerLayout);
        jPanelIssuerLayout.setHorizontalGroup(
            jPanelIssuerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIssuerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIssuerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanelIssuerLayout.createSequentialGroup()
                        .addGroup(jPanelIssuerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIssuer)
                            .addComponent(jLabel4))
                        .addGap(72, 72, 72)
                        .addGroup(jPanelIssuerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanelIssuerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSearch5, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jTextFieldSearch3))))
                .addGap(18, 18, 18)
                .addGroup(jPanelIssuerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSearch3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLogout3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelIssuerLayout.setVerticalGroup(
            jPanelIssuerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIssuerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIssuerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIssuer)
                    .addComponent(jTextFieldSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanelIssuerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearch3)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSearch5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanelIssuerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIssue))
                .addGap(18, 18, 18)
                .addComponent(jButtonLogout3)
                .addContainerGap())
        );

        jPanelMain.add(jPanelIssuer, "3");

        jLabel1.setText("External User");

        jLabel2.setText("Search By:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Title", "Author", "Item Type" }));

        jList4.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList4);

        jButtonLogout4.setText("Log Out");
        jButtonLogout4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonLogout4ActionPerformed(evt);
            }
        });

        jButtonSearch4.setText("Search");

        javax.swing.GroupLayout jPanelExternalUserLayout = new javax.swing.GroupLayout(jPanelExternalUser);
        jPanelExternalUser.setLayout(jPanelExternalUserLayout);
        jPanelExternalUserLayout.setHorizontalGroup(
            jPanelExternalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExternalUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelExternalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelExternalUserLayout.createSequentialGroup()
                        .addGroup(jPanelExternalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExternalUserLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldSearch4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLogout4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelExternalUserLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jButtonSearch4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelExternalUserLayout.setVerticalGroup(
            jPanelExternalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExternalUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelExternalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSearch4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch4))
                .addGap(18, 18, 18)
                .addGroup(jPanelExternalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelExternalUserLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLogout4))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelMain.add(jPanelExternalUser, "4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Fires on login button pressed, authenticates user.
    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonLoginActionPerformed
    {//GEN-HEADEREND:event_jButtonLoginActionPerformed
        // Check with Signincontroller if password is correct.
        SignInController signIn = new SignInController(currentSelection,
                new String(jPasswordField.getPassword()));
        if (signIn.Authenticate())
        {
            // Change Panel to selected user on login
            changeCard(currentSelection);
        }
        else
        {
            // Authentication failed.
            JOptionPane.showMessageDialog(null, "Authentication failed : incorrect password!");
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonLogoutActionPerformed
    {//GEN-HEADEREND:event_jButtonLogoutActionPerformed
        changeCard(-1); //Login card name
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExportActionPerformed

    private void jButtonLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogout1ActionPerformed
        changeCard(-1);
    }//GEN-LAST:event_jButtonLogout1ActionPerformed

    private void jButtonLogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogout2ActionPerformed
        changeCard(-1);
    }//GEN-LAST:event_jButtonLogout2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButtonLogout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogout3ActionPerformed
        changeCard(-1);
    }//GEN-LAST:event_jButtonLogout3ActionPerformed

    private void jButtonLogout4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogout4ActionPerformed
        changeCard(-1);
    }//GEN-LAST:event_jButtonLogout4ActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddMember;
    private javax.swing.JButton jButtonChange;
    private javax.swing.JButton jButtonChangePrivilege;
    private javax.swing.JButton jButtonExport;
    private javax.swing.JButton jButtonIssue;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonLogout1;
    private javax.swing.JButton jButtonLogout2;
    private javax.swing.JButton jButtonLogout3;
    private javax.swing.JButton jButtonLogout4;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonRemoveMember;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonSearch2;
    private javax.swing.JButton jButtonSearch3;
    private javax.swing.JButton jButtonSearch4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCataloguer;
    private javax.swing.JLabel jLabelIssuer;
    private javax.swing.JLabel jLabelPasswordHint;
    private javax.swing.JLabel jLabelReportsManager;
    private javax.swing.JLabel jLabelSearchHint;
    private javax.swing.JLabel jLabelSysAdmin;
    private javax.swing.JLabel jLabelUserHint;
    private javax.swing.JList jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList jListUsers;
    private javax.swing.JPanel jPanelCataloguer;
    private javax.swing.JPanel jPanelExternalUser;
    private javax.swing.JPanel jPanelIssuer;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelReportsManager;
    private javax.swing.JPanel jPanelSysAdmin;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldSearch2;
    private javax.swing.JTextField jTextFieldSearch3;
    private javax.swing.JTextField jTextFieldSearch4;
    private javax.swing.JTextField jTextFieldSearch5;
    // End of variables declaration//GEN-END:variables

    private void changeCard(int currentSelection)
    {
        card.show(jPanelMain, Integer.toString(currentSelection));
    }
}
